ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - bcrypt

overrides:
  ajv@<8.18.0: '>=8.18.0'
  hono@<4.11.10: '>=4.11.10'
  hono@<4.11.7: '>=4.11.7'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@<10.2.1: '>=10.2.1'
